branch-defaults:
  master:
    environment: cg-test-dev
    group_suffix: null
deploy:
  artifact: ./Dockerrun.aws.json
environment-defaults:
  cg-test-dev:
    branch: null
    repository: null
global:
  application_name: cg_test
  branch: null
  default_ec2_keyname: cg-test
  default_platform: Docker 1.12.6
  default_region: eu-central-1
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
